"""An adventure program, bring the player a world of unknowns and choices."""


__author__ = "730400848"

from random import randint
player: str = "Name"
adventure_score: int = 0

def main() -> None:
    greet()
    football()
    return None


def greet() -> None:
    """An introduction to the adventure for the player."""
    global player
    player = str(input("Before we begin, what is your name? "))
    print(f"Perfect, Nice to meet you {player}! This is quite the journey, and to see how well you do I will be keeping score right here. 5 points for telling me your name already!")
    global adventure_score
    adventure_score += 5
    first_part_of_intro_statement: str = (f"Well, {player} today is quite the day.")
    second_part_of_intro_statement: str = ("There is a number of different events that will be quite the test to any competitor that dares to enter them.")
    third_part_of_intro_statement: str = ("There's a test of mind, body and spirit.")
    fourth_part_of_intro_statement: str = ("And if you pass, you will be seen as one of the top competitors in the nation.")
    print(f"{first_part_of_intro_statement}\n{second_part_of_intro_statement}\n{third_part_of_intro_statement}\n{fourth_part_of_intro_statement}")
    ready = str(input("Are you ready to be seen as one of the best? Yes or No? "))
    if ready == "Yes" or ready == "yes":
        body_explanation: str = ("The test of body is American football. Score then stop a computer to win.")
        mind_explanation: str = ("the test of mind. A test that has you attempt to guess a number generated by a secret guest.")
        spirit_explanation: str = ("the test of spirit is fill in later.")
        print("Well, before you commit, let me explain what each of the tests are.")
        print(f"{body_explanation}\nNext is {mind_explanation}\nAnd finally there is {spirit_explanation}")
        second_ready = str(input("Now that you know what the tests are, I will ask again: Are you ready? Yes or No? "))
        if second_ready == "yes" or second_ready == "Yes":
            print("Perfect, then let us continue on.")
            return None
        else:
            print("Well, I do not have time for those that are inpercise or not committed to the journey.")
            last_chance = str(input("So, I will ask you one more time. Do you want to take this journey? And be precise. Yes or No? "))
    else:
        print("Well, I do not have time for those that are not committed to the journey.")
        last_chance = str(input("So, I will ask you one more time. Do you want to take this journey? And be precise. Yes or No? "))
    if last_chance == "yes" or last_chance == "Yes" or last_chance == "No" or last_chance == "no":
        if last_chance == "yes" or last_chance == "Yes":
            body_explanation: str = ("The test of body is American football. Score then stop a computer to win.")
            mind_explanation: str = ("the test of mind. A test that has you attempt to guess a number generated by a secret guest.")
            spirit_explanation: str = ("the test of spirit is fill in later.")
            print("Perfect! Well, before you commit, let me explain what each of the tests are.")
            print(f"{body_explanation}\nNext is {mind_explanation}\nAnd finally there is {spirit_explanation}")
            second_ready = str(input("Now that you know what the tests are, I will ask again: Are you ready? Yes or No? "))
        if second_ready == "yes" or second_ready == "Yes":
            print("Perfect, then let us continue on.")
            return None
        else:
            print(f"Well then, it is clear you do not want to be great. If you ever get that feeling you know where to return to. Goodbye {player}.")
            return None
    else:
        print(f"I have no time for those who cannot be precise! Goodbye {player}")
        return None
    print(adventure_score)


def football() -> int:
    """The physical football game of the adventure."""
    print(f"So, {player} you have chosen football. Good choice. Let me explain the rules")
    print(f"For each 5 yards you gain, you will get an additional point towards your adventure score.\nAnd, if you happen to score a touchdown, you'll get 6 point.")
    print(f"Special teams are for the wierdos of the world, so no extra points nor kickoffs.\nThe ball will always start on the twenty five.")
    football_affirm: str = input(f"Make sense squirt? Yes or No:\n")
    football_affirm: int = ord(football_affirm[0])
    while football_affirm < ord("Y") and football_affirm == ord("n"):
        print("Well, I guess I can explain the rules again if you really need it.")
        print(f"For each 5 yards you gain, you will get an additional point towards your adventure score.\nAnd, if you happen to score a touchdown, you'll get 6 point.")
        print(f"Special teams are for the wierdos of the world, so no extra points nor kickoffs.\nThe ball will always start on the twenty five.")
        second_football_affirm: str = input("Got it now? Be precise this time: Yes or No\n")
    print("Perfect, now I'll need you to pick a team to lead")
    print("First, there's the runners. And you guessed it they are a run first team.\nThey can run it down your throat and stop the run in return.\nHowever, they stink in the air, both side of the ball, don't matter.")
    print("Next, we got the Ace's.\n They are the opposites of the runners.\n Great both at and against passing while being mirror images of themselves on the grounds")
    print("Finally, we have the Joes. Average at everything.")
    team_choice: int = int(input(f"So what will it be for you {player}. Team 1: the Joes, team 2: the Runners or team 3: The Aces?\n1, 2 or 3: "))
    while int(team_choice) > 3 or int(team_choice) < 1:
            team_choice: int = int(input("Well, I'm afraid I am going to need to ask you again. And be precise this time.\nWill it be Team 1: the Joes, team 2: the Runners or team 3: The Aces?\n 1, 2 or 3: "))
    if team_choice == 1 or 2:
        if team_choice == 1:
            team_choice: str = "the Joes"
        else:
            team_choice: str = "the Runners"
    else:
        team_choice: str = "the Aces"
    print(f"Ah, {team_choice}. Decent choice I'd say")
    opposing_team: int = randint(1,2)
    if team_choice == "the Aces" or "the Runners":
        if team_choice == "the Aces":
            if opposing_team == 1:
                opposing_team: str = "the Joes"
            else:
                opposing_team: str = "the Runners"
        else:
            if opposing_team == 1:
                opposing_team: str = "the Aces"
            else: 
                opposing_team: str = "the Joes"
    else:
        if opposing_team == 1:
            opposing_team: str = "the Aces"
        else:
            opposing_team: str = "the Runners"
    print(f"Today you will be playing {opposing_team}.")
    input("You ready to ball out?: ")
    print("Of course you are!!!")
    

if __name__ == "__main__":
  main()