"""An adventure program, bringing the player a world of unknowns and choices."""
"""Attempted above and beyond #9, creation of a game loop in the second half of the path_choice function(). i= 1, while i > 0."""
"""Attempted above and beoynd #10, created a third game, rock paper scissors, on top of the other two games, leader and mental."""


__author__ = "730400848"


from random import randint
player: str = "Name"
points: int = 0
way_to_go_emoji: str = "\U0001f643"
wink_emoji: str = "\U0001F609"


def main() -> None:
    greet()
    path_choice()
    return None


def greet() -> None:
    """An introduction to the adventure for the player."""
    global player
    player = str(input("Before we begin, what is your name: "))
    print(f"Perfect, Nice to meet you {player}! This is quite the journey, and, to see how well you do, I will be keeping score right here. 5 points for telling me your name already!")
    global points
    points += 5
    first_part_of_intro_statement: str = ("Today is quite the day.")
    second_part_of_intro_statement: str = ("There is a number of different events that will be quite the test to any competitor that dares to enter them.")
    third_part_of_intro_statement: str = ("There's a test of mind, a test of leader, and a test of rock paper scissors.")
    fourth_part_of_intro_statement: str = ("And, using our point system, we'll see how much of a talent you are.")
    print(f"{first_part_of_intro_statement}\n{second_part_of_intro_statement}\n{third_part_of_intro_statement}\n{fourth_part_of_intro_statement}")
    input("*Press Enter to Continue.*")
    mind_explanation: str = ("the test of mind.\nA test that has you attempt to guess a number, using clues, generated by a secret guest.")
    spirit_explanation: str = ("the test of spirit.\nA test that has you make decisions to get yourself off a sinking ship and to safety.")
    rps_explanation: str = (f"the test of rock paper scissors. Battle a computer in an age old test of skill.\n{wink_emoji}")
    print("Well, before you commit, let me explain what each of the tests are.")
    print(f"Either, you may undertake {mind_explanation}\nOr there is {spirit_explanation}\nOr there is {rps_explanation}")
    input("*Press Enter to Continue.*")
    print("Perfect, then let us continue on. Let's walk for a bit to give you a choice as to what game you shall choose.")


def path_choice() -> None:
    print("Perfect we're here. Time to make your decision about which game you'll choose")
    print(f"Game 1: Mental, Game 2: Leader or Game 3: Rock paper scissors.")
    print("And, of course, if you arent cut out for greatness, you may leave now. Let's called that Game 4: Coward.")
    game_choice: int = int(input(f"What shall it be?\n1, 2, 3 or 4: "))
    global points
    if game_choice == 1 or game_choice == 2 or game_choice == 3:
        if game_choice == 1 or game_choice == 2:
            if game_choice == 1:
                points += mental(points)
            if game_choice == 2:
                leader()
        else:
            rock_paper()
    else:
        print("Well then, I guess then that this is the end of our journey.")
        print(f"Although it isnt much, you still scored {points} points in our short time together. Congrats, I guess.")
        print(f"Goodbye, {player}")
        exit()
    i = 1
    while i >= 1:
        print(f"Well that was quite the preformance. Currently you have {points} points.")
        path_choice_affirm: str = input("What do you say about another round?\nAnd it need not be the same game.\nYes or No: ")
        path_choice_affirm: str = path_choice_affirm.lower()
        path_choice_affirm: int = ord(path_choice_affirm[0])
        if path_choice_affirm != ord("y"):
            last_chance: str = input("Are you sure you want to quit?\nBe precise now.\nYes or No: ")
            last_chance: str = last_chance.lower()
            last_chance: int = ord(last_chance[0])
            if last_chance == ord("y"):
                    print(f"Well it was quite the journey. You happened to score {points} points, which is alright I guess.")
                    print(f"If you ever choose to desire greatness again, you know where to return to. Goodbye {player}.")
                    exit()
        if path_choice_affirm == ord("y"): 
            print(f"Good, I am glad to see you aren't content\nSo what will the next game be.")
            print("Game 1: Mental, Game 2: Leader or Game 3: Rock paper scissors.")
            second_game_choice: int = int(input("1, 2 or 3: "))
            if second_game_choice == 1 or second_game_choice ==2:
                if second_game_choice == 1:
                    points += mental(points)   
                else:
                    leader()
            else:
                rock_paper()
    return None


def mental(points_mental: points) -> int:
    """Creation of the number guessing game."""
    print("I see, you have chosen to play the mental game.\nMust be a nerd.\nI kid I kid.")
    input("*Press Enter to Continue.*")
    print("In this game you'll attempt to guess, using clues, what the randomly number generated is.")
    print("For each guess wrong, you'll lose one potential adventure point.")
    input("*Press Enter to Continue*")
    print("And since there are a total of 10 numbers (1-10), if you were to get it right on the first choice, you'd get 10 points.")
    print("Also there are hard and easy clues. The hard clues give double the points.\nThat is, if you can get them correct.")
    input("*Press Enter to Continue*")
    print("Let's get this party started!")      
    random_number: int = randint(1,10)
    difficulty_choice: str = input("Do you want hard or easy clues?\nHard or Easy: ")
    difficulty_choice: str = difficulty_choice.lower()
    difficulty_choice: int = ord(difficulty_choice[0])
    player_guess: str = "Guess"
    random_number: int = randint(1,10)
    iteration_mental: int = 0
    max_points_mental: int = 11 #since mental_iteration base value after 1 run is 1, so 11-1= 10 which is max points
    while player_guess != random_number:
        if random_number == 1:
            if difficulty_choice == ord("e"):
                print("The most elementary number.")
                player_guess: int = int(input("Guess: "))
            else:
                print("Veterans Day.")
                player_guess: int = int(input("Guess: "))
        if random_number == 2:
            if difficulty_choice == ord("e"):
                print("All evens are divisible by this number.")
                player_guess: int = int(input("Guess: "))
            else:
                print("Fishy boy.")
                player_guess: int = int(input("Guess: "))
        if random_number == 3: 
            if difficulty_choice == ord("e"):
                print("triangles.")
                player_guess: int = int(input("Guess: "))
            else:
                print("lonely boy wheeling.")
                player_guess: int = int(input("Guess: "))
        if random_number == 4:
            if difficulty_choice == ord("e"):
                print("squares and rectangle share this common number for their properties.")
                player_guess: int = int(input("Guess: "))
            else:
                print("Starting year for popular video game, EU4.")
                player_guess: int = int(input("Guess: "))
        if random_number == 5:
            if difficulty_choice == ord("e"):
                print("the 4th prime number of the set.")
                player_guess: int = int(input("Guess: "))
            else:
                print("Best day of the month to have birthday on.")
                player_guess: int = int(input("Guess: "))
        if random_number == 6:
            if difficulty_choice == ord("e"):
                print("1 + 100000000000 * 0 + 5 =")
                player_guess: int = int(input("Guess: "))
            else:
                print("Modern Warfare 2")
                player_guess: int = int(input("Guess: "))
        if random_number == 7:
            if difficulty_choice == ord("e"):
                print("sqaure root of 49")
                player_guess: int = int(input("Guess: "))
            else:
                print("Most exciting game in sports.")
                player_guess: int = int(input("Guess: "))
        if random_number == 8:
            if difficulty_choice == ord("e"):
                print("don't hate, appreciate")
                player_guess: int = int(input("Guess: "))
            else:
                print("the second digit in the amount of teams that make the NCAA tournament")
                player_guess: int = int(input("Guess: "))
        if random_number == 9:
            if difficulty_choice == ord("e"):
                print("cloud ____")
                player_guess: int = int(input("Guess: "))
            else:
                print("sixth digit of pi")
                player_guess: int = int(input("Guess: "))
        if random_number == 10:
            if difficulty_choice == ord("e"):
                print("The largest number of the set.")
                player_guess: int = int(input("Guess: "))
            else:
                print("The original december.")
                player_guess: int = int(input("Guess: "))
        iteration_mental += 1
        if player_guess == random_number:
            print(f"Correct!\nIt only took you {iteration_mental} guesses.")
            input("*Press Enter to Continue*")
        else:
            print(f"Incorrect, try again.\nGuesses: {iteration_mental}")
    if difficulty_choice == ord("e"):
        points_mental += (max_points_mental - iteration_mental - points_mental)
    else: 
        points_mental += (2 * (max_points_mental - iteration_mental) - points_mental)
    return points_mental


def leader() -> None:
    """Creation of the leader game."""
    print(f"Welp Mr. {player}leader, you've transferred us to a sinking ship.")
    print("It was sailing East, when, right around noon, a sudden explosion in the engine put a crater in the side of the ship.")
    print(f"Way to go! {way_to_go_emoji}")
    input("*Press Enter to Continue.*")
    print(f"Well Mr. {player}leader, there's no time to waste if hope to get off this ship.\nAlive, that is.")
    print(f"Lead the way!")
    input("*Press Enter to Continue.*")
    print(f"Each \"good decision\" you make will get you an additional point.")
    print(f"Each \"poor decision\" you make won't take away from your points.\nBut it'll take away a life.")
    print("You get two of those. I believe in second chances.")
    print("And, if you manage to get us back to shore, you'll get an additional ten points.")
    input("*Press enter to continue.*")
    print(f"I know what you're thinking,\nI've wasted our time with these points that won't matter if we don't get off this ship.")
    print(f"But who knows, maybe someone will recover my notebook. I do use waterproof ink.\n{wink_emoji}")
    print(f"Also we've got you Mr. {player}leader. So we're in great hands.\n{way_to_go_emoji}")
    input("*Press Enter to Continue*")
    print("So, whats your first decision?")
    lives: int = 2
    global points
    choice_1_1: str = ("Check to see how bad damage is?")
    choice_1_2: str = ("Use emergency flare gun and call for help.")
    choice_1_3: str = ("Look for materials.")
    print(f"So what is your first decision:\n1) {choice_1_1}\n2) {choice_1_2}\n3) {choice_1_3}")
    choice_1: int = int(input("1, 2 or 3: "))
    while choice_1 <= 0 or choice_1 >= 4:
        print("That wasn't an option. Pick one this time, before we run out of time.")
        choice_1: int = int(input("1, 2 or 3: "))
    if choice_1 == 2 or choice_1 == 1:
        print("Poor decision.")
        lives -= 1
        if choice_1 == 2:
            print("Poor decision.")
            print(f"Mr. {player}leader, were in the middle of the ocean and its day time. No one will see it.")
            print("Well, we still need materials so lets go get some.")
            print("Remember, that poor decision cost you a life. Do better.")
        else:
            print("Poor decision.")
            print(f"Mr. {player}leader, did I not tell you that the ship was going down?\nWhat's the point of looking.")
            print("Well, we still need materials so lets go get some.")
            print("Remember, that poor decision cost you a life. Do better.")
    else:
        print("Good choice, easy decision, good job. Remember, that's one point.")
        points += 1
    print(f"Lives: {lives}")
    input("*Press Enter to Continue.*")
    print("Well, you found the emergency supplies kit and materials for a raft. Let's get to work with that.")
    print("Altough, while looking it seems as though you cut yourself.")
    print("How are you going to heal yourself?")
    choice_2_1: str = ("Look through the emergency supplies kit.")
    choice_2_2: str = ("Rip off part of your shirt and rap it around the gash.")
    choice_2_3: str = ("Who really cares, a little blood never hurt anybody, and we have limited time.")
    print(f"1) {choice_2_1}\n2) {choice_2_2}\n3) {choice_2_3}")
    choice_2: int = int(input("1, 2 or 3: "))
    while choice_2 <= 0 or choice_2 >= 4:
        print("That wasn't an option. Pick one this time, before we run out of time.")
        choice_2: int = int(input("1, 2 or 3: "))
    if choice_2 == 1 or choice_2 == 2: 
        print("Good choice.")
        points += 1
        if choice_2 == 1: 
            print("Well, it seems as though you found a nice, albeit kinda small, bandaid.")
            print("As long as you don't end up in the water you should be fine.")
        else:
            print("Your shirt should work. What kinda material is that anyway?")
            print("Looks like a gause, ugly, but perfect for this situation.")
    else:
        print("Poor choice.")
        lives -= 1
        if lives == 0:
            print("You really aren't a good leader, I guess we're going down with the ship.")
            print("I know someone will find my notebook to transfer your score at least.")
            return None
        print("Why would you choose that? That does not make anysense.")
        print("But, we have no time to deliberate any further.")
    input("*Press Enter to Continue*")
    print(f"Lives: {lives}")
    print("Oh no! While were talking and applying your decision, some of the materials slid off the ship.")
    print("We lost most of the food and all of the water out of the supply bag!\nAlso most of the raft materials.")
    choice_3_1: str = "Go into the water and get them."
    choice_3_2: str = "Risk going back under the deck to get more materials."
    print(f"So what is the decision:\n1) {choice_3_1}\n2) {choice_3_2}")
    choice_3: int = int(input("1 or 2: "))
    while choice_3 <= 0 or choice_3 >= 3:
        print("That wasn't an option. Pick one this time, before we run out of time.")
        choice_3: int = int(input("1 or 2: "))
    if choice_3 == 1:
        if choice_2 == 2:
            points += 1 
            print(f"Good decision!\nYou were able to somehow recover all of the raft materials.")
            print(f"And good thing your shirt is basically gause.\nYou got no blood in the water.\nYou know sharks love blood.")
        else:
            lives -= 1
            print("Poor decision.")
            print("With that small bandaind you had on, you got blood in the water.")
            print(f"With the blood in the water, you attracted the sharks.\nEveryone knows shark always smell blood in the water.")
            print(f"Hence why i'm not suprised a shark took a bite out of you")
            if lives == 0:
                print("You really aren't a good leader, you can't survive that much blood loss.")
                print("I know someone will find my notebook to transfer your score at least.")
                return None
            print("At least you're still alive, barely")
    else: 
        prob_survival: int = randint(1,3)
        if prob_survival == 1 or prob_survival == 2:
            print("Close call there, almost got dragged down into the water.")
            print("And, you got all the materials.")
            points += 1
        else:
            print("Poor decision, you got sucked down with the rest of the ship.")
            lives -= 1
            if lives == 0:
                print("I guess you really aren't a good leader. You killed us.")
                print("I know someone will find my notebook to transfer your score at least.")
                return None
            print("At least I was able to salvage some materials.")
    print(f"Lives: {lives}")
    input("*Press Enter to Continue*")
    print("Perfect, with those materials we were able to build this raft.")
    print(f"Well Mr. {player}leader, which way we sailing.")
    choice_4_1: str = ("East")
    choice_4_2: str = ("West")
    choice_4_3: str = ("North")
    print(f"So what is the decision:\n1) {choice_4_1}\n2) {choice_4_2}\n3) {choice_4_3}")
    choice_4: int = int(input("1, 2 or 3: "))
    while choice_4 <= 0 or choice_4 >= 4:
        print("That wasn't an option. Pick one this time, before we run out of time.")
        choice_4: int = int(input("1, 2 or 3: "))
    if choice_4 == 1 or choice_4 == 3:
        print("Poor decision")
        print("Didn't I tell you the ship was sailing East to start!!!")
        lives -= 1
        if lives == 0:
            print("I guess you really aren't a good leader. You killed us.")
            print("I know someone will find my notebook to transfer your score at least.")
            return None
        print("Good thing I got a handy dandy paddle to turn us around before we run out of supplies.")
    else: 
        print("Great choice.")
        print("You're a keen listener.")
        print("The ship shouldn't too far off the coast so we should see the shore in no time.")
        points += 1
    print(f"Lives: {lives}")
    input("*Press Enter to Continue.*")
    print("I guess there is one more issue that might need your discretion.")
    print("Remember when we had to salvage the materials to make up for those that fell off the ship.")
    print("Well, we didn't grab any of the food or water. What should we do?")
    choice_5_1: str = ("Try and catch fish off the side of the boat and make a water distiller")
    choice_5_2: str = ("Try and tough it out without and food or water.")
    print(f"So what is the decision:\n1) {choice_5_1}\n2) {choice_5_2}")
    choice_5: int = int(input("1 or 2: "))
    while choice_5 <= 0 or choice_5 >= 4:
        print("That wasn't an option. Pick one this time, before we run out of time.")
        choice_5: int = int(input("1 or 2: "))
    if choice_5 == 1:
        print("Poor decision.")
        print("*After a while of attempting the solution.*")
        print("Well, it appears as though we got pushed off course.")
        print("Didn't I tell you we werent that far off shore, so we dont need any food or water.")
        print("You really need to listen.")
        lives -= 1
        if lives == 0:
            print("I guess you really aren't a good leader. You killed us.")
            print("I know someone will find my notebook to transfer your score at least.")
            return None
        print("Good thing I kept this paddle, I'll get us to shore.")
    else:
        print("You are a really keen listener.")
        print("You remembered that we we're only a little bit away from shore and we will be able to last.")
        print("By not looking, it'll allow us focus on the course of our raft.")
        print("We wouldn't want to veer off course.")
        print("We'll see that shore any minure now.")
        points += 1
    input("*Press Enter to Continue.*")
    print("*After an hour of sailing, you finally see the shore.*")
    print("Wow, You actually got us back to shore.")
    print(f"Good job Mr. {player}leader!")
    print("That's 10 points.")
    points += 10
    return None


def rock_paper () -> None:
    """Creation of rock paper scissors adventure."""
    print("I see, you have chose the classic game of rock paper scissors.")
    print(f"Of course we'll play best of 3.\nWho doesn't?")
    input("*Press Enter to Continue*")
    """1 = rock, 2 = paper, 3 = scissor"""
    print(f"You'll input yours first and I promise I won't cheat.{wink_emoji}")
    print("And for every series you win, you'll get two points.\nBut, if you sweep, you'll get 3.")
    input("*Press Enter to Continue*")
    user_win: int = 0
    comp_win: int = 0
    iteration_rps: int = 0
    global points
    while user_win < 2 and comp_win < 2:
        comp_rps = randint (1,3)
        print("Rock, paper, scissor")
        user_rps: int = int(input("What you shooting\n1) Rock\n2) Paper\n3) Scissor\n1, 2 or 3: "))
        if user_rps == comp_rps:
            print("Wash")
            print(f"Series stands at {player}: {user_win} and Computer: {comp_win}.")
            input("*Press Enter to Continue*")
        if user_rps == 1 and comp_rps == 2:
            print("Computer wins!\nPaper beats rock!")
            iteration_rps += 1
            comp_win += 1
            print(f"Series stands at {player}: {user_win} and Computer: {comp_win}.")
            input("*Press Enter to Continue*")
        if user_rps == 1 and comp_rps == 3:
            print(f"{player} wins!\nRock beats scissor!")
            iteration_rps += 1
            user_win += 1
            print(f"Series stands at {player}: {user_win} and Computer: {comp_win}.")
            input("*Press Enter to Continue*")
        if user_rps == 2 and comp_rps == 1:
            print(f"{player} wins!\nPaper beats rock!")
            iteration_rps += 1
            user_win += 1
            print(f"Series stands at {player}: {user_win} and Computer: {comp_win}.")
            input("*Press Enter to Continue*")
        if user_rps == 2 and comp_rps == 3:
            print("Computer wins!\nScissor beats paper!")
            iteration_rps += 1
            comp_win += 1
            print(f"Series stands at {player}: {user_win} and Computer: {comp_win}.")
            input("*Press Enter to Continue*")
        if user_rps == 3 and comp_rps == 2:
            print(f"{player} wins!\nScissor beats paper!")
            iteration_rps += 1
            user_win += 1
            print(f"Series stands at {player}: {user_win} and Computer: {comp_win}.")
            input("*Press Enter to Continue*")
        if user_rps == 3 and comp_rps == 1:
            print("Computer wins!\nRock beats scissor!")
            iteration_rps += 1
            comp_win += 1
            print(f"Series stands at {player}: {user_win} and Computer: {comp_win}.")
            input("*Press Enter to Continue*")
    if user_win == 2:
        print(f"Congrats {player}. You've bested the computer. Alright I guess.")
        print("This is a game of luck so...")
        if iteration_rps == 2:
            points += 3
        else:
            points += 2
    else:
        print("Ha ha, the computer wins.\nYou stink.\nYou aren't as skillful.")
    input("*Press Enter to Continue*")
    return None


if __name__ == "__main__":
    main()