"""An adventure program, bring the player a world of unknowns and choices."""


__author__ = "730400848"

from random import randint
player: str = "Name"
points: int = 0

def main() -> None:
    greet()
    path_choice()
    return None


def greet() -> None:
    """An introduction to the adventure for the player."""
    global player
    player = str(input("Before we begin, what is your name: "))
    print(f"Perfect, Nice to meet you {player}! This is quite the journey, and to see how well you do I will be keeping score right here. 5 points for telling me your name already!")
    global points
    points += 5
    first_part_of_intro_statement: str = ("today is quite the day. Yada yada yada")
    second_part_of_intro_statement: str = ("There is a number of different events that will be quite the test to any competitor that dares to enter them.")
    third_part_of_intro_statement: str = ("There's a test of mind, body and spirit.")
    fourth_part_of_intro_statement: str = ("And if you pass, you will be seen as one of the top competitors in the nation.")
    print(f"{first_part_of_intro_statement}\n{second_part_of_intro_statement}\n{third_part_of_intro_statement}\n{fourth_part_of_intro_statement}")
    input("*Press Enter to Continue.*")
    body_explanation: str = ("The test of body is American football. Score then stop a computer to win.")
    mind_explanation: str = ("the test of mind. A test that has you attempt to guess a number generated by a secret guest.")
    spirit_explanation: str = ("the test of spirit is fill in later.")
    print("Well, before you commit, let me explain what each of the tests are.")
    print(f"{body_explanation}\nNext is {mind_explanation}\nAnd finally there is {spirit_explanation}")
    input("*Press Enter to Continue.*")
    print("Perfect, then let us continue on. Let's walk for a bit to give you a choice as to what game you shall choose.")


def path_choice() -> None:
    print("Perfect we're here. Time to make your decision about which game you'll choose")
    print(f"Game 1: Physical, Game 2: Mental, Game 3: Leader.\nAnd, of course, if you arent cut out for greatness, you may leave now. Let's called that Game 4: Coward.")
    game_choice: int = int(input(f"What shall it be?\n1, 2, 3 or 4: "))
    if game_choice == 1 or game_choice == 2 or game_choice == 3:
        if game_choice == 1 or game_choice == 2:
            if game_choice == 1:
                football()
            else:
                mental()
        else:
            leader()
    else:
        print("Well then, I guess then that this is the end of our journey.")
        print(f"Although it isnt much, you still scored {points} points in our short time together. Congrats, I guess.")
        print(f"Goodbye, {player}")
        exit()
    i = 1
    while i >= 1:
        path_choice_affirm: str = input(f"Well that was quite the preformance. Currently you have {points}.\nWhat do you say about another round?\nAnd it need not be the same game.\nYes or No: ")
        path_choice_affirm: str = path_choice_affirm.lower()
        path_choice_affirm: int = ord(path_choice_affirm[0])
        if path_choice_affirm != ord("y"):
            last_chance: str = input("Are you sure you want to quit?\nBe precise now.\nYes or No: ")
            last_chance: str = last_chance.lower()
            last_chance: int = ord(last_chance[0])
            if last_chance == ord("y"):
                    print(f"Well it was quite the journey. You happened to score {points} points, which is alright I guess.")
                    print(f"If you ever choose to desire greatness again, you know where to return to. Goodbye {player}.")
                    exit()
        if path_choice_affirm == ord("y"): 
            print(f"Good, I am glad to see you aren't content\nSo what will the next game be.\nGame 1: Physical, Game 2: Mental, Game 3: Spiritual.")
            second_game_choice: int = int(input("1, 2, 3: "))
            if second_game_choice == 1 or second_game_choice == 2:
                if second_game_choice == 1 :
                    football()
                else:
                    mental()
            else:
                spiritual()


def football() -> None:
    """The physical football game of the adventure."""
    print(f"So, {player} you have chosen football. Good choice. Let me explain the rules")
    print(f"For each 5 yards you gain, you will get an additional point towards your adventure score.\nAnd, if you happen to score a touchdown, you'll get 6 point.")
    print(f"Special teams are for the wierdos of the world, so no extra points nor kickoffs.\nThe ball will always start on the twenty five.")
    input("*Press Enter to Continue.*")
    print("Perfect, now I'll need you to pick a team to lead")
    print("First, there's the runners.\nYou guessed it they are a run first team.\nGreat on the ground on both sides of the ball.\nBut, if you take them off of it they stink, defense or offense, don't matter")
    input("*Press Enter to Continue*")
    print("Next, we got the Ace's.\n They are the opposites of the runners.\nGreat both at and against passing while being mirror images of themselves on the grounds")
    input("*Press Enter to Continue*")
    team_choice: int = int(input(f"So what will it be for you {player}. Team 1: the Runners or Team 2: The Aces?\n1 or 2: "))
    while type(team_choice) != int:
        team_choice: int = int(input(f"So what will it be for you {player}. Team 1: the Runners or Team 2: The Aces?\n1 or 2: "))
    while int(team_choice) > 2 or int(team_choice) < 1:
            team_choice: int = int(input("Well, I'm afraid I am going to need to ask you again. And be precise this time.\nWill it be team 1: the Runners or team 2: The Aces?\n 1 or 2: "))
    if team_choice == 1:
        team_choice: str = "the Runners"
    else:
        team_choice: str = "the Aces"
    print(f"Ah, {team_choice}. Decent choice I'd say")
    opposing_team: str = "Name"
    if team_choice == "the Aces": 
        opposing_team: str = "the Runners"
    else:    
        opposing_team: str = "the Aces"
    print(f"Today you will be playing {opposing_team}.")
    input("You ready to ball out?: ")
    print("Of course you are!!!")
    """Defining the stats for each team"""
    print("Seeing as though it is more exiciting for a game consisting of two drives, you start on offense")
    input("*Press Enter to Continue*")
    max_yard: int = 75
    yard_gain = 0
    iteration: int = 1
    threshold_homerun_pass: int = 95
    threshold_20yard_pass: int = 85
    threshold_10yard_pass: int = 65
    threshold_5yard_pass: int = 30
    threshold_incomplete_pass: int = 10
    yard_on_play: int = 0
    aces_completion_rate: int = .08
    aces_passD: int = .025
    aces_rushing_success: int = .04
    aces_rushD: int = .005
    aces_homerun_rate: int = .001
    runners_completion_rate: int = .045
    runners_passD: int = .005
    runners_rushing_success: int = .08
    runners_rushD: int = .025
    runners_homerun_rate: int = .002
    yard_per_point: int = 5
    yard_point_touchdown: int = ((yard_on_play - (yard_gain - max_yard)) // yard_per_point)
    pass_result_rng: int = randint(0,100)
    defense_success: int = randint(0,100)
    plays_before_first: list[int] = []
    iteration: int = 1
    yard_point: int = (yard_on_play // yard_per_point)
    def firstdown(iterat: int) -> None:
        """A first down function."""
        global iteration
        if sum(plays_before_first) >= 10:
            plays_before_first.clear()
            iterat = 1
            return 
        else:
            iterat += 1
            return None
    while abs(yard_gain) < max_yard and iteration <= 4: #offense
        pass_result_rng: int = randint(0,100)
        defense_success: int = randint(0,100)
        global points
        offense_play_choice: str = input("What is your play call.\nPass or Run: ")
        offense_play_choice: str = offense_play_choice.lower()
        offense_play_choice: int = ord(offense_play_choice[0])
        if offense_play_choice == ord("p"):
            if team_choice == "the Aces":
                aces_threshold: int = (pass_result_rng + (pass_result_rng * aces_completion_rate))
                runners_passD_tresh: int = (defense_success * runners_passD)
                pass_offense_AvR: int = aces_threshold - runners_passD_tresh
                if pass_offense_AvR <= threshold_incomplete_pass:
                    print("Interception!")
                    yard_gain: int = -200
                if pass_offense_AvR > threshold_incomplete_pass and pass_offense_AvR <= threshold_5yard_pass:
                    yard_on_play = 0
                    iteration += 1
                    plays_before_first.append(yard_on_play)
                    print(plays_before_first)
                    firstdown(iteration)
                    print(f"Down number {iteration}")
                if pass_offense_AvR > threshold_5yard_pass and pass_offense_AvR <= threshold_10yard_pass:
                    yard_gain += 5
                    yard_on_play = 5
                    if yard_gain >= max_yard:
                        print("Touchdown")
                        points += 6 + yard_point_touchdown
                    else: 
                        print("5 yard gain!")
                        yard_point + yard_point
                        points += int(yard_on_play // yard_per_point)
                        iteration += 1
                        plays_before_first.append(yard_on_play)
                        print(plays_before_first)
                        firstdown(iteration)
                        print(f"Down number {iteration}")
                if pass_offense_AvR > threshold_10yard_pass and pass_offense_AvR <= threshold_20yard_pass:
                    yard_gain += 10
                    yard_on_play = 10
                    if yard_gain >= max_yard:
                        print("Touchdown!")
                        points += 6 + yard_point_touchdown
                    else:
                        print("10 yard gain!")
                        points += int(yard_on_play / yard_per_point)
                        iteration += 1
                        plays_before_first.append(yard_on_play)
                        print(plays_before_first)
                        firstdown(iteration)
                        print(f"Down number {iteration}")
                if pass_offense_AvR > threshold_20yard_pass and pass_offense_AvR <= threshold_homerun_pass:
                    yard_gain += 20
                    yard_on_play = 20
                    if yard_gain >= max_yard:
                        print("Touchdown!")
                        points += 6 + yard_point_touchdown
                    else: 
                        print("20 yard gain!")
                        points += int(yard_on_play / yard_per_point)
                        iteration += 1
                        plays_before_first.append(yard_on_play)
                        print(plays_before_first)
                        firstdown(iteration)
                        print(f"Down number {iteration}")
                if aces_threshold - runners_passD_tresh > threshold_homerun_pass:
                    yard_gain = (max_yard - yard_gain)
                    yard_on_play = yard_gain
                    print("Touchdown!")
                    points += 6 + yard_point_touchdown
                    iteration = 5


def mental() -> None:
    """Creation of the number guessing game."""
    print("I see, you have chosen to play the mental game.\nMust be a nerd.\nI kid I kid.")
    input("*Press Enter to Continue.*")
    print("In this game you'll attempt to guess, using clues, what the random number generated is.")
    print("For each guess wrong, you'll lose one potential adventure point.")
    input("*Press Enter to Continue*")
    print("And since there are a total of 10 numbers, if you were to get it right on the first choice, you'd get 10 points.")
    print("Also there are hard and easy clues. The hard clues give double the points.\nThat is, if you can get them correct.")
    input("*Press Enter to Continue*")
    print("Let's get this party started!")      
    random_number: int = randint(1,10)
    difficulty_choice: str = input("Do you want hard or easy clues?\nHard or Easy: ")
    difficulty_choice: str = difficulty_choice.lower()
    difficulty_choice: int = ord(difficulty_choice[0])
    player_guess: str = "Guess"
    random_number: int = randint(1,10)
    iteration_mental: int = 0
    max_points_mental: int = 11 #since mental_iteration base value after 1 run is 1, so 11-1= 10 which is max points
    points_mental: int = max_points_mental - iteration_mental
    global points
    while player_guess != random_number:
        if random_number == 1:
            if difficulty_choice == ord("e"):
                print("The most elementary number.")
                player_guess: int = int(input("Guess: "))
            else:
                print("Veterans Day.")
                player_guess: int = int(input("Guess: "))
        if random_number == 2:
            if difficulty_choice == ord("e"):
                print("All evens are divisible by this number.")
                player_guess: int = int(input("Guess: "))
            else:
                print("Fishy boy.")
                player_guess: int = int(input("Guess: "))
        if random_number == 3: 
            if difficulty_choice == ord("e"):
                print("triangles.")
                player_guess: int = int(input("Guess: "))
            else:
                print("lonely boy wheeling.")
                player_guess: int = int(input("Guess: "))
        if random_number == 4:
            if difficulty_choice == ord("e"):
                print("squares and rectangle share this common number for their properties.")
                player_guess: int = int(input("Guess: "))
            else:
                print("Starting year for popular video game, EU4.")
                player_guess: int = int(input("Guess: "))
        if random_number == 5:
            if difficulty_choice == ord("e"):
                print("the 4th prime number of the set.")
                player_guess: int = int(input("Guess: "))
            else:
                print("Best day of the month to have birthday on.")
                player_guess: int = int(input("Guess: "))
        if random_number == 6:
            if difficulty_choice == ord("e"):
                print("1 + 100000000000 * 0 + 5 =")
                player_guess: int = int(input("Guess: "))
            else:
                print("Modern Warfare 2")
                player_guess: int = int(input("Guess: "))
        if random_number == 7:
            if difficulty_choice == ord("e"):
                print("sqaure root of 49")
                player_guess: int = int(input("Guess: "))
            else:
                print("Most exciting game in sports.")
                player_guess: int = int(input("Guess: "))
        if random_number == 8:
            if difficulty_choice == ord("e"):
                print("don't hate, appreciate")
                player_guess: int = int(input("Guess: "))
            else:
                print("the second digit in the amount of teams that make the NCAA tournament")
                player_guess: int = int(input("Guess: "))
        if random_number == 9:
            if difficulty_choice == ord("e"):
                print("cloud ____")
                player_guess: int = int(input("Guess: "))
            else:
                print("sixth digit of pi")
                player_guess: int = int(input("Guess: "))
        if random_number == 10:
            if difficulty_choice == ord("e"):
                print("The largest number of the set.")
                player_guess: int = int(input("Guess: "))
            else:
                print("The original december.")
                player_guess: int = int(input("Guess: "))
        iteration_mental += 1
        if player_guess == random_number:
            print(f"Correct!\nIt only took you {iteration_mental} guesses.")
            input("*Press Enter to Continue*")
        else:
            print(f"Incorrect, try again.\nGuesses: {iteration_mental}")
    if difficulty_choice == ord("e"):
        points += (max_points_mental - iteration_mental)
    else: 
        points += (2 * (max_points_mental - iteration_mental))
    return None


def leader() -> None:
    """Creation of the leader game."""
    print(f"Welp Mr. {player}leader, you've transferred us to a sinking ship.")
    print("It was sailing East, when, right around noon, a sudden explosion in the engine, put a crater in the side of the ship.")
    way_to_go_emoji: str = "\U0001f643"
    print(f"Way to go! {way_to_go_emoji}")
    input("*Press Enter to Continue.*")
    print(f"Well Mr. {player}leader, there's no time to waste if hope to get off this ship.\nAlive, that is.")
    print(f"Lead the way!")
    input("*Press Enter to Continue.*")
    print("Each correct decision you make will get you an additional point.")
    print(f"Each bad decision you make won't take away from your points.\nBut it'll take away a life.")
    print("You get two of those. I believe in second chances.")
    print("And, if you manage to get us back to shore, you'll get an additional ten points.")
    input("*Press enter to continue.*")
    print("I know what you're thinking,\nI've wasted our time with these points that won't matter if we don't get off this ship.")
    wink_emoji: str = "\U0001F609"
    print(f"But who knows, maybe someone will recover my notebook. I do use waterproof ink.\n{wink_emoji}")
    print(f"Also we've got you Mr. {player}leader. So we're in great hands.\n{way_to_go_emoji}")
    input("*Press Enter to Continue*")
    print("So, whats your first decision?")
    lives: int = 2
    global points
    choice_1_1: str = ("Check to see how bad damage is?")
    choice_1_2: str = ("Use emergency flare gun and call for help.")
    choice_1_3: str = ("Look for materials.")
    print(f"So what is your first decision:\n1) {choice_1_1}\n2) {choice_1_2}\n3) {choice_1_3}")
    choice_1: int = int(input("1, 2 or 3: "))
    while choice_1 <= 0 or choice_1 >= 4:
        print("That wasn't an option. Pick one this time, before we run out of time.")
        choice_1: int = int(input("1, 2 or 3: "))
    if choice_1 == 2 or choice_1 == 1:
        print("Poor decision.")
        lives -= 1
        if choice_1 == 2:
            print(f"Mr. {player}leader, were in the middle of the ocean and its day time. No one will see it.")
            print("Well, we still need materials so lets go get some.")
        else:
            print(f"Mr. {player}leader, did I not tell you that the ship was going down?\nWhat's the point of looking.")
            print("Well, we still need materials so lets go get some.")
    else:
        print("Easy choice, good job. Remember, that's one point.")
        points += 1
    print(f"Lives: {lives}")
    input("*Press Enter to Continue.*")
    print("Well, you found the emergency supplies kit and materials for a raft. Let's get to work with that.")
    print("Altough, while looking it seems as though you cut yourself.")
    print("How are you going to heal yourself?")
    choice_2_1: str = ("Look through the emergency supplies kit.")
    choice_2_2: str = ("Rip off part of your shirt and rap it around the gash.")
    choice_2_3: str = ("Who really cares, a little blood never hurt anybody, and we have limited time.")
    print(f"1) {choice_2_1}\n2) {choice_2_2}\n3) {choice_2_3}")
    choice_2: int = int(input("1, 2 or 3: "))
    while choice_2 <= 0 or choice_2 >= 4:
        print("That wasn't an option. Pick one this time, before we run out of time.")
        choice_2: int = int(input("1, 2 or 3: "))
    if choice_2 == 1 or choice_2 == 2: 
        print("Good choice.")
        points += 1
        if choice_2 == 1: 
            print("Well, it seems as though you found a nice, albeit kinda small, bandaid.")
            print("As long as you don't end up in the water you should be fine.")
        else:
            print("Your shirt should work. What kinda material is that anyway?")
            print("Looks like a gause, ugly, but perfect for this situation.")
    else:
        print("Poor choice.")
        lives -= 1
        if lives == 0:
            print("You really aren't a good leader, I guess we're going down with the ship.")
            print("I know someone will find my notebook to transfer your score at least.")
            return None
        print("Why would you choose that? That does not make anysense.")
        print("But, we have no time to deliberate any further.")
    input("*Press Enter to Continue*")
    print(f"Lives: {lives}")
    print("Oh no! While were talking and applying your decision, some of the materials slid off the ship.")
    print("We lost most of the food and all of the water out of the supply bag!\nAlso most of the raft materials.")
    choice_3_1: str = "Go into the water and get them."
    choice_3_2: str = "Risk going back under the deck to get more materials."
    print(f"So what is the decision:\n1) {choice_3_1}\n2) {choice_3_2}")
    choice_3: int = int(input("1 or 2: "))
    while choice_3 <= 0 or choice_3 >= 3:
        print("That wasn't an option. Pick one this time, before we run out of time.")
        choice_3: int = int(input("1 or 2: "))
    if choice_3 == 1:
        if choice_2 == 2:
            points += 1 
            print(f"Good decision!\nYou were able to somehow recover all of the raft materials.")
            print(f"And good thing your shift is basically gause.\nNo blood got in the water.\nYou know sharks love blood.")
        else:
            lives -= 1
            print("Poor decision.")
            print(f"You got blood in the water, which attracted the sharks.\nEveryone knows shark always smell blood in the water.")
            print(f"Hence why i'm not suprised a shark took a bite out of you")
            if lives == 0:
                print("You really aren't a good leader, you can't survive that much blood loss.")
                print("I know someone will find my notebook to transfer your score at least.")
                return None
            print("At least you're still alive, barely")
    else: 
        prob_survival: int = randint(1,3)
        if prob_survival == 1 or prob_survival == 2:
            print("Close call there, almost got dragged down into the water.")
            print("And, you got all the materials.")
            points += 1
        else:
            print("Poor decision, you got sucked down with the rest of the ship.")
            lives -= 1
            if lives == 0:
                print("I guess you really aren't a good leader. You killed us.")
                print("I know someone will find my notebook to transfer your score at least.")
                return None
            print("At least I was able to salvage some materials.")
    print(f"Lives: {lives}")
    input("*Press Enter to Continue*")
    print("Perfect, with those materials we were able to build this raft.")
    print(f"Well Mr. {player}leader, which way we sailing.")
    choice_4_1: str = ("East")
    choice_4_2: str = ("West")
    choice_4_3: str = ("North")
    print(f"So what is the decision:\n1) {choice_4_1}\n2) {choice_4_2}\n3) {choice_4_3}")
    choice_4: int = int(input("1, 2 or 3: "))
    while choice_4 <= 0 or choice_4 >= 4:
        print("That wasn't an option. Pick one this time, before we run out of time.")
        choice_4: int = int(input("1, 2 or 3: "))
    if choice_4 == 1 or choice_4 == 3:
        print("Poor decision")
        print("Didn't I tell you the ship was sailing East to start!!!")
        lives -= 1
        if lives == 0:
            print("I guess you really aren't a good leader. You killed us.")
            print("I know someone will find my notebook to transfer your score at least.")
            return None
        print("Good thing I got a handy dandy paddle to turn us around before we run out of supplies.")
    else: 
        print("Great choice.")
        print("You're a keen listener.")
        print("The ship shouldn't too far off the coast so we should see the shore in no time.")
        points += 1
    print(f"Lives: {lives}")
    input("*Press Enter to Continue.*")
    print("I guess there is one more issue that might need your discretion.")
    print("Remember when we had to salvage the materials to make up for those that fell off the ship.")
    print("Well, we didn't grab any of the food or water. What should we do?")
    choice_5_1: str = ("Try and catch fish off the side of the boat and make a water distiller")
    choice_5_2: str = ("Try and tough it out without and food or water.")
    print(f"So what is the decision:\n1) {choice_5_1}\n2) {choice_5_2}")
    choice_5: int = int(input("1 or 2: "))
    while choice_5 <= 0 or choice_5 >= 4:
        print("That wasn't an option. Pick one this time, before we run out of time.")
        choice_5: int = int(input("1 or 2: "))
    if choice_5 == 1:
        print("Poor decision.")
        print("*After a while of attempting the solution.*")
        print("Well, it appears as though we got pushed off course.")
        print("Didn't I tell you we werent that far off shore.")
        print("You really need to listen.")
        lives -= 1
        if lives == 0:
            print("I guess you really aren't a good leader. You killed us.")
            print("I know someone will find my notebook to transfer your score at least.")
            return None
        print("Good thing I kept this paddle, I'll get us to shore.")
    else:
        print("You are a really keen listener.")
        print("You remembered that we we're only a little bit away from shore and we will be able to last.")
        print("It'll allow us focus on the course of our raft.\nWouldn't want to veer off course.")
        print("We'll see that shore any minure now.")
        points += 1
    input("*Press Enter to Continue.*")
    print("*After an hour of sailing, you finally see the shore.")
    print("Wow, You actually got us back to shore.")
    print(f"Good job Mr. {player}leader!")
    points += 10
    return None
    
if __name__ == "__main__":
    main()